services:
  mysql:
    image: mariadb:10.6
    container_name: mysql-standalone
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test
      MYSQL_USER: sa
      MYSQL_PASSWORD: password
    
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  users-mysql:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: users-mysql
    restart: unless-stopped
    depends_on:
      - mysql
    ports:
      - "8086:8086"

volumes:
  mysql-data:
